MACHINE COMP_1seq1_OPS
 
 ABSTRACT_VARIABLES counter, max_counter, cond1, check_boolexp, check_BLOCK, check_BECOME, check_IF, check_CASE, check_SEQUENCE, check_WHILE, check_OPER_CALL
 INVARIANT counter : NAT & max_counter : NAT& cond1 : BOOL & check_boolexp : BOOL & check_BLOCK: INT &  check_BECOME: INT &  check_IF: INT &  check_CASE: INT &  check_SEQUENCE: INT &  check_WHILE : INT & check_OPER_CALL : INT
 INITIALISATION counter:= 1|| max_counter:= 1024|| cond1:=TRUE|| check_boolexp:=TRUE|| check_BLOCK:= 0 ||  check_BECOME:= 0 ||   check_IF:= 0 ||   check_CASE:= 0 ||   check_SEQUENCE:= 0 ||   check_WHILE := 0|| check_OPER_CALL := 0
OPERATIONS
ID00000=
BEGIN skip 
END

; ID00001=
BEGIN skip 
END

; ID00002=
BEGIN skip 
END

; ID00003=
BEGIN skip 
END

; ID00004=
BEGIN skip 
END

; ID00005=
BEGIN skip 
END

; ID00006=
BEGIN skip 
END

; ID00007=
BEGIN skip 
END

; ID00008=
BEGIN skip 
END

; ID00009=
BEGIN skip 
END

; ID00010=
BEGIN skip 
END

; ID00011=
BEGIN skip 
END

; ID00012=
BEGIN skip 
END

; ID00013=
BEGIN skip 
END

; ID00014=
BEGIN skip 
END

; ID00015=
BEGIN skip 
END

; ID00016=
BEGIN skip 
END

; ID00017=
BEGIN skip 
END

; ID00018=
BEGIN skip 
END

; ID00019=
BEGIN skip 
END

; ID00020=
BEGIN skip 
END

; ID00021=
BEGIN skip 
END

; ID00022=
BEGIN skip 
END

; ID00023=
BEGIN skip 
END

; ID00024=
BEGIN skip 
END

; ID00025=
BEGIN skip 
END

; ID00026=
BEGIN skip 
END

; ID00027=
BEGIN skip 
END

; ID00028=
BEGIN skip 
END

; ID00029=
BEGIN skip 
END

; ID00030=
BEGIN skip 
END

; ID00031=
BEGIN skip 
END

; ID00032=
BEGIN skip 
END

; ID00033=
BEGIN skip 
END

; ID00034=
BEGIN skip 
END

; ID00035=
BEGIN skip 
END

; ID00036=
BEGIN skip 
END

; ID00037=
BEGIN skip 
END

; ID00038=
BEGIN skip 
END

; ID00039=
BEGIN skip 
END


 END