MACHINE
    TestSet_BRANCH_nested_else_case

OPERATIONS
    verdict <-- TEST_0_opnested_else_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_1_opnested_else_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_2_opnested_else_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_3_opnested_else_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_4_opnested_else_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_5_opnested_else_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END
END