MACHINE
    TestSet_PATH_duoseq_while_nestedwhile

OPERATIONS
    verdict <-- TEST_0_opduoseq_while_nestedwhile =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_1_opduoseq_while_nestedwhile =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_2_opduoseq_while_nestedwhile =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_3_opduoseq_while_nestedwhile =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_4_opduoseq_while_nestedwhile =
        ANY kk WHERE kk : BOOL THEN verdict := kk END
END