MACHINE
    TestSet_PATH_nested_while_whileseq

OPERATIONS
    verdict <-- TEST_0_opnested_while_whileseq =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_1_opnested_while_whileseq =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_2_opnested_while_whileseq =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_3_opnested_while_whileseq =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_4_opnested_while_whileseq =
        ANY kk WHERE kk : BOOL THEN verdict := kk END
END