MACHINE
    TestSet_BRANCH_nested_case_else

OPERATIONS
    verdict <-- TEST_0_opnested_case_else =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_1_opnested_case_else =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_2_opnested_case_else =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_3_opnested_case_else =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_4_opnested_case_else =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_5_opnested_case_else =
        ANY kk WHERE kk : BOOL THEN verdict := kk END
END