MACHINE
    TestSet_CLAUSE_triple_case_else_while

OPERATIONS
    verdict <-- TEST_0_optriple_case_else_while =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_1_optriple_case_else_while =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_2_optriple_case_else_while =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_3_optriple_case_else_while =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_4_optriple_case_else_while =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_5_optriple_case_else_while =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_6_optriple_case_else_while =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_7_optriple_case_else_while =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_8_optriple_case_else_while =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_9_optriple_case_else_while =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_10_optriple_case_else_while =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_11_optriple_case_else_while =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_12_optriple_case_else_while =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_13_optriple_case_else_while =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_14_optriple_case_else_while =
        ANY kk WHERE kk : BOOL THEN verdict := kk END
END