MACHINE
    TestSet_BRANCH_triple_while_case_else

OPERATIONS
    verdict <-- TEST_0_optriple_while_case_else =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_1_optriple_while_case_else =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_2_optriple_while_case_else =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_3_optriple_while_case_else =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_4_optriple_while_case_else =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_5_optriple_while_case_else =
        ANY kk WHERE kk : BOOL THEN verdict := kk END
END