MACHINE
    TestSet_PATH_triple_else_case_case

OPERATIONS
    verdict <-- TEST_0_optriple_else_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_1_optriple_else_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_2_optriple_else_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_3_optriple_else_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_4_optriple_else_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_5_optriple_else_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_6_optriple_else_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_7_optriple_else_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_8_optriple_else_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_9_optriple_else_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_10_optriple_else_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_11_optriple_else_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_12_optriple_else_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_13_optriple_else_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_14_optriple_else_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_15_optriple_else_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_16_optriple_else_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_17_optriple_else_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END
END