MACHINE
    TestSet_CODE_triple_else_else_while

OPERATIONS
    verdict <-- TEST_0_optriple_else_else_else =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_1_optriple_else_else_else =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_2_optriple_else_else_else =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_3_optriple_else_else_else =
        ANY kk WHERE kk : BOOL THEN verdict := kk END
END