MACHINE
    TestSet_CLAUSE_triple_while_else_else

OPERATIONS
    verdict <-- TEST_0_optriple_while_else_else =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_1_optriple_while_else_else =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_2_optriple_while_else_else =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_3_optriple_while_else_else =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_4_optriple_while_else_else =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_5_optriple_while_else_else =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_6_optriple_while_else_else =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_7_optriple_while_else_else =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_8_optriple_while_else_else =
        ANY kk WHERE kk : BOOL THEN verdict := kk END
END