MACHINE
    TestSet_CODE_triple_case_case_case

OPERATIONS
    verdict <-- TEST_0_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_1_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_2_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_3_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_4_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_5_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_6_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_7_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_8_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_9_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_10_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_11_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_12_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_13_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_14_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_15_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_16_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_17_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_18_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_19_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_20_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_21_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_22_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_23_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_24_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_25_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_26_optriple_case_case_case =
        ANY kk WHERE kk : BOOL THEN verdict := kk END
END