MACHINE
    TestSet_CLAUSE_OC_WHILEINSIDE

OPERATIONS
    verdict <-- TEST_0_opOC_WHILEINSIDE =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_1_opOC_WHILEINSIDE =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_2_opOC_WHILEINSIDE =
        ANY kk WHERE kk : BOOL THEN verdict := kk END;

    verdict <-- TEST_3_opOC_WHILEINSIDE =
        ANY kk WHERE kk : BOOL THEN verdict := kk END
END